#import packages
import MrMs as m
Sveta = m.Miss("Svetlana", 18)
Masha = m.Miss("Maria", 17)
Anna = m.Miss("Anna", 20)
Vasya = m.Mister("Vasya", 18)
Sveta.setRate()
Masha.setRate()
Anna.setRate(1000)
Vasya.setRate()
MissItmo2014 = m.Rate(Anna, Sveta, Masha)
# MissItmo2014.showWinner()
MissItmo2014.candidatesSort()
# MissItmo2014.candidatesSort("age")
# MissItmo2014.candidatesSort("name")
